baseurl = "https://astromberg.github.io/"
title = "Stromberg Labs"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "default"
  description = "Place for my projects"
  sidebar = "A place for my projects."

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""

  [[params.navlinks]]
  name = "About"
  url = "/about/"

